version: "3"

services:
  ifconfig:
    image: "iproute/ifconfig:latest"
    restart: always
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./GeoLite2-City.mmdb:/opt/app/GeoLite2-City.mmdb
      - ./ipipfree.ipdb:/opt/app/ipipfree.ipdb
      - ./ip2region.db:/opt/app/ip2region.db
      - ./qqwry.dat:/opt/app/qqwry.dat