version: "3"

services:
  ifconfig:
    image: "iproute/ifconfig:latest"
    restart: always
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./GeoLite2-City.mmdb:/opt/app/GeoLite2-City.mmdb
      - ./ipipfree.ipdb:/opt/app/ipipfree.ipdb